# Generated by Django 4.2.1 on 2023-05-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberReserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start_reserved', models.DateField()),
                ('date_end_reserved', models.DateField()),
                ('email_reserved', models.CharField(max_length=255)),
                ('phone_reserved', models.CharField(max_length=255)),
            ],
        ),
    ]
